name: Deploy docs

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-20
          profile: minimal
          components: rust-src
      - name: Build docs
        run: |
          mkdir doc
          for target in \
            x86_64-apple-darwin \
            aarch64-unknown-linux-gnu \
            aarch64-unknown-none-softfloat \
            riscv32imac-unknown-none-elf \
            riscv64imac-unknown-none-elf \
            riscv64imac-unknown-none-elf \
            mipsel-unknown-linux-gnu
          do
            rustup target add ${target}
            cargo doc --target ${target}
            mv target/${target}/doc doc/${target}
          done
          for target in x86_64-unknown-linux-gnu
          do
            rustup target add ${target}
            cargo doc --target ${target}
            cargo doc --target ${target} -Z build-std=core,alloc
            mv target/${target}/doc doc/${target}
          done
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
